on:
  push:
    branches: main
  schedule:
    - cron: '0 12 * * MON'

name: Render README

jobs:
  render:
    name: Render README
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-pandoc@v2
      - name: Install rmarkdown
        run: |
          Rscript -e 'install.packages("rmarkdown")'
          Rscript -e 'install.packages("here")'
          Rscript -e 'install.packages("ggplot2")'
          Rscript -e 'install.packages("plotly")'
      - name: Render README
        run: Rscript -e 'rmarkdown::render("README.Rmd", output_format = "md_document")'
      - name: Commit results
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add -A .
          git commit -m 'Re-build README.Rmd' || echo "No changes to commit"
          git push origin || echo "No changes to commit"